AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Lint/RescueException:
  Exclude:
    - 'lib/one44-cli/optparse.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/one44-cli/optparse.rb'

Naming/FileName:
  Exclude:
    - 'lib/one44-cli.rb'

Style/Documentation:
  Enabled: false